name: Publish Storybook

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # Chromatic이 git 히스토리 필요

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - run: npm ci || npm install   # lock 파일 없으면 install
      - run: npm run build-storybook --if-present

      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-once-uploaded
