name: Publish Storybook

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - run: npm install --legacy-peer-deps

      - run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
